language: java
jdk:
  - openjdk11
  - openjdk10
  - openjdk9
  - oraclejdk14
  - oraclejdk13
  - oraclejdk12

cache:
  directories:
  - $HOME/.m2  # maven packages

install:
  mvn --version

script:
  mvn test
